### ISSUE TITLE
First and last name visible during event

### ISSUE THREAD

**Issue by AcidicPeridot** [DeathChaos25/PQ_Patches#3] opened 2023-09-06 15:03 UTC
The patch works fine in battles and menus and whatnot, but in any dialogue event, the protagonist's full name is shown (ex:"Kotone Shiomi") when everyone else only has their first name. (ex:"Morgana", "Ryuji") It looks really out of place.

**Comment by DeathChaos25** [comment] 2023-09-06 18:32
This is **_not_** an issue caused by this patch, check your mods to see which one is causing this issue.

**Comment by AcidicPeridot** [comment] 2023-09-07 01:26
Oh wow- it looks like this is caused by the _Talk Animation Fix_ patch for some reason. Is there an updated version of that patch that fixes the issue?

![image](https://github.com/DeathChaos25/PQ_Patches/assets/106778581/accc61dc-96c2-44ac-9b4e-69e703f4bf61)

Funnily enough, [the site that showcases both the Canon Name patch and the Talk Animation Fix](https://shrinefox.com/guides/2021/08/15/using-pq2-patches/) shows this exact issue in the image above.

**Comment by ShrineFox** [comment] 2023-09-20 11:56
The issue has now been fixed in the latest release: https://github.com/DeathChaos25/PQ_Patches/releases/tag/v1.1.0

**Closed as completed** 2023-09-20 12:30 UTC
